name: codio-publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: rm -rf .git

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@master
        with:
          client-id: ${{ secrets.CODIO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_SECRET_ID }}
          dir: ./
          course-name: "Demo Github Actions" 
          assignment-name: "Assignment 1"
          changelog: ${{ github.event.head_commit.message }}
          yml: "./.github/yaml_map"